version: '3.2'

services:

  ai4e-things-mariadb:
    image: mariadb:10.6.14
    container_name: ai4e-things-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dlgcdxlgjzdsys
      MYSQL_DATABASE: ai4e_things
      MYSQL_USER: ai4e_things
      MYSQL_PASSWORD: 789612543Ab1234
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
       - ./deploy/data/mariadb:/var/lib/mysql
    restart: always
    networks:
      ai4e_net:
        ipv4_address: 172.20.0.116

  ai4e-things-emqx:
    image: emqx/emqx:5.1.4
    container_name: ai4e-things-emqx
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    # volumes:
    #   - ./deploy/emqx/emqx_data:/opt/emqx/data
    #   - ./deploy/emqx/emqx_log:/opt/emqx/log
    #   - ./deploy/emqx/emqx_etc:/opt/emqx/etc
    networks:
      ai4e_net:
        ipv4_address: 172.20.0.117

networks:
  ai4e_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16